name: Sync to GitLab

on:
  push:
    branches:
      - main  # or whichever branch you want to track

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "dragon731012"
        git config user.email "dragon73101@gmail.com"

    - name: Add or update GitLab remote
      run: |
        git remote set-url gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/potato12341/code.git || git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/potato12341/code.git
        git fetch gitlab

    - name: Pull from GitLab (rebase to avoid merge conflicts)
      run: |
        git pull --rebase gitlab main  # or the branch you want to sync

    - name: Push to GitLab
      run: |
        git push gitlab main  # or the branch you want to sync
