name: GitHub to GitLab Sync

on:
  push:
    branches:
      - main  # or any branch you want to sync

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://gitlab.com/potato12341/code.git
          git fetch gitlab

      - name: Push changes to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git push https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/potato12341/code.git HEAD:main
